#!/usr/bin/env bash

if [ "$#" -ne 2 ]; then
    echo "usage: $0 input.wasm output.wasm"
    exit 1
fi

wasm-opt \
    --llvm-memory-copy-fill-lowering \
    --signext-lowering \
    --disable-bulk-memory \
    --llvm-nontrapping-fptoint-lowering \
    --mvp-features \
    --disable-sign-ext \
    --disable-multivalue \
    --disable-simd \
    $1 \
    -o $2

exit $?