[package]
name = "spacewasm_std-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
spacewasm = { path = "..", features = ["strict-assertions"] }
spacewasm-fuzzing = { path = "../crates/fuzzing", features = ["differential"] }

[[bin]]
name = "validate"
path = "fuzz_targets/validate.rs"
test = false
doc = false
bench = false

[[bin]]
name = "validate_differential"
path = "fuzz_targets/validate_differential.rs"
test = false
doc = false
bench = false

[[bin]]
name = "no_traps"
path = "fuzz_targets/no_traps.rs"
test = false
doc = false
bench = false

[[bin]]
name = "malformed"
path = "fuzz_targets/malformed.rs"
test = false
doc = false
bench = false

[profile.release]
debug = 1
