[target.'cfg(target_arch = "riscv64")']
runner = """qemu-system-riscv64 \
                -icount shift=0 \
                -bios none \
                -cpu rv64 \
                -machine virt \
                -m 256M \
                -nographic \
                -semihosting-config enable=on,target=native \
                -kernel"""

[target.'cfg(target_arch = "riscv32")']
runner = """qemu-system-riscv32 \
                -icount shift=0 \
                -bios none \
                -cpu rv32 \
                -machine virt \
                -m 256M \
                -nographic \
                -semihosting-config enable=on,target=native \
                -kernel"""

[target.'cfg(target_arch = "arm")']
runner = """qemu-system-arm \
                -icount shift=0 \
                -cpu cortex-m4 \
                -machine netduinoplus2 \
                -nographic \
                -semihosting-config enable=on,target=native \
                -kernel"""